import { StyleSheet } from 'react-native';

// Color constants used by HomeScreen styles
export const ACCENT_COLOR = '#F29D4E';
export const ACCENT_COLOR_SOFT = 'rgba(242, 157, 78, 0.12)';
export const ACCENT_COLOR_SOFT_2 = 'rgba(242, 157, 78, 0.16)';
export const ACCENT_COLOR_SOFT_5 = 'rgba(242, 157, 78, 0.22)';
export const WARM_BG = '#1A120D';
export const WARM_BG_2 = '#22160F';
export const WARM_BG_3 = '#2C1C12';
export const WARM_BORDER = '#3B2A1E';
export const WARM_BORDER_SOFT = 'rgba(242, 157, 78, 0.14)';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: WARM_BG,
  },
  content: {
    width: '100%',
    paddingTop: 8,
    gap: 18,
  },
  headerRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  circleIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: WARM_BORDER,
    backgroundColor: WARM_BG_2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.34)',
    backgroundColor: 'rgba(242, 157, 78, 0.16)',
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusPillConnected: {
    borderColor: '#4A6E3A',
    backgroundColor: 'rgba(42, 63, 42, 0.9)',
  },
  statusPillDisconnected: {
    borderColor: '#7A3A3A',
    backgroundColor: 'rgba(63, 42, 42, 0.9)',
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 99,
    backgroundColor: ACCENT_COLOR,
  },
  statusDotConnected: {
    backgroundColor: '#4CAF50',
  },
  statusDotError: {
    backgroundColor: '#F44336',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#F6C089',
  },
  pageTitle: {
    color: '#FFF0DF',
    fontWeight: '800',
    marginBottom: 2,
  },
  ringsField: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  staticRing: {
    position: 'absolute',
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.22)',
  },
  travelWave: {
    position: 'absolute',
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.28)',
  },
  orbOuter: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.34)',
    backgroundColor: 'rgba(242, 157, 78, 0.12)',
  },
  glowOrb: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  glowPulse: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
    backgroundColor: ACCENT_COLOR_SOFT,
    shadowColor: '#F6B873',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 34,
    elevation: 16,
  },
  orbRing: {
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F29D4E',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 18,
    elevation: 12,
  },
  orbInner: {
    width: '86%',
    height: '86%',
    borderRadius: 999,
    backgroundColor: '#0D1122',
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.38)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  waveWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  waveBar: {
    width: 4,
    borderRadius: 99,
    backgroundColor: ACCENT_COLOR,
  },
  responseGlyphWrap: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  responseGlyph: {
    color: '#7FD3FF',
    fontSize: 26,
    fontWeight: '900',
  },
  idleDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: ACCENT_COLOR,
  },
  heroCopyWrap: {
    alignSelf: 'center',
    maxWidth: 300,
    alignItems: 'center',
  },
  sectionLabel: {
    marginTop: 2,
    marginBottom: -4,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.2,
    color: '#7C84A6',
  },
  card: {
    borderWidth: 1,
    borderColor: WARM_BORDER,
    backgroundColor: WARM_BG_2,
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 10,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  rowTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    color: '#FFF0DF',
    fontSize: 15,
    fontWeight: '700',
  },
  rowSubtitle: {
    marginTop: 3,
    color: '#C6A98D',
    fontSize: 12,
  },
  iconTile: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.28)',
    backgroundColor: 'rgba(242, 157, 78, 0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconGlyph: {
    color: '#F6C089',
    fontSize: 16,
    fontWeight: '800',
  },
  separator: {
    marginLeft: 68,
    borderBottomWidth: 1,
    borderBottomColor: WARM_BORDER,
  },
  modeGridWrap: {
    marginTop: -2,
    marginBottom: 8,
    marginHorizontal: 12,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.2)',
    backgroundColor: WARM_BG_3,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 6,
  },
  modeChip: {
    width: '48%',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.18)',
    backgroundColor: WARM_BG_2,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeChipActive: {
    borderColor: ACCENT_COLOR,
    backgroundColor: 'rgba(242, 157, 78, 0.18)',
  },
  modeChipText: {
    color: '#DCE4FF',
    fontSize: 13,
    fontWeight: '700',
  },
  modeChipTextActive: {
    color: '#F8D1A6',
  },
  historyWrap: {
    marginHorizontal: 12,
    marginTop: -2,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.22)',
    backgroundColor: WARM_BG_2,
    gap: 8,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 2,
    paddingHorizontal: 2,
  },
  historyHeaderTitle: {
    color: '#FFF0DF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
  },
  historyHeaderMeta: {
    color: '#C6A98D',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  historyMetaPill: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: ACCENT_COLOR_SOFT,
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.16)',
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(242, 157, 78, 0.16)',
    backgroundColor: WARM_BG_3,
  },
  historyDivider: {
    height: 1,
    marginLeft: 40,
    marginTop: 1,
    marginBottom: 1,
    backgroundColor: WARM_BORDER_SOFT,
  },
  historyLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  historyDotWrap: {
    width: 20,
    height: 20,
    borderRadius: 99,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ACCENT_COLOR_SOFT_2,
    borderWidth: 1,
    borderColor: ACCENT_COLOR_SOFT_5,
  },
  historyDot: {
    width: 6,
    height: 6,
    borderRadius: 99,
    backgroundColor: ACCENT_COLOR,
  },
  historyTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  historyCommand: {
    color: '#FFF0DF',
    fontSize: 13,
    fontWeight: '700',
  },
  historyTime: {
    marginTop: 2,
    color: '#C6A98D',
    fontSize: 10,
  },
  historyArrow: {
    color: '#B88D69',
    fontSize: 18,
    fontWeight: '700',
  },
  infoTitle: {
    color: '#FFF0DF',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  infoMeta: {
    marginTop: 6,
    color: '#C6A98D',
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  chevron: {
    color: '#B88D69',
    fontSize: 18,
    lineHeight: 18,
    fontWeight: '700',
  },
  navWrapper: {
    backgroundColor: WARM_BG,
  },
  bottomNav: {
    borderTopWidth: 1,
    borderTopColor: WARM_BORDER,
    backgroundColor: WARM_BG,
    paddingTop: 6,
    paddingBottom: 4,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  navItem: {
    alignItems: 'center',
    minWidth: 70,
    flex: 1,
    paddingVertical: 6,
  },
  navGlyph: {
    color: '#A87A5A',
    fontSize: 18,
    fontWeight: '700',
  },
  navGlyphActive: {
    color: ACCENT_COLOR,
    fontSize: 18,
    fontWeight: '800',
  },
  navLabel: {
    marginTop: 3,
    color: '#A87A5A',
    fontWeight: '500',
    fontSize: 11,
  },
  navLabelActive: {
    marginTop: 3,
    color: ACCENT_COLOR,
    fontWeight: '700',
    fontSize: 11,
  },
  activeDot: {
    marginTop: 4,
    width: 5,
    height: 5,
    borderRadius: 99,
    backgroundColor: ACCENT_COLOR,
  },
});
