import { StyleSheet } from 'react-native';

export const ACCENT_COLOR = '#F29D4E';
export const WARM_BG = '#1A120D';
export const WARM_BG_2 = '#22160F';
export const WARM_BG_3 = '#2C1C12';
export const WARM_BORDER = '#3B2A1E';

export default StyleSheet.create({
  root: { flex: 1, backgroundColor: WARM_BG },
  content: { width: '100%', paddingTop: 12, gap: 18 },
  headerRow: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8 },
  circleIcon: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: WARM_BORDER, backgroundColor: WARM_BG_2, alignItems: 'center', justifyContent: 'center' },
  backArrow: { color: '#E8C8A2', fontSize: 20, fontWeight: '700' },
  pageTitle: { color: '#FFF0DF', fontWeight: '800' },
  sectionLabel: { marginTop: 6, marginBottom: -4, fontSize: 12, fontWeight: '700', letterSpacing: 1.2, color: '#B88D69' },
  card: { paddingHorizontal: 12, paddingVertical: 14, borderWidth: 1, borderColor: WARM_BORDER, backgroundColor: WARM_BG_2 },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  rowLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  iconTile: { borderRadius: 11, borderWidth: 1, borderColor: WARM_BORDER, backgroundColor: WARM_BG_3, alignItems: 'center', justifyContent: 'center' },
  rowTextWrap: { flex: 1, minWidth: 0 },
  rowTitle: { color: '#FFF0DF', fontSize: 15, fontWeight: '700' },
  rowSubtitle: { marginTop: 3, color: '#C6A98D', fontSize: 12 },
  separator: { marginVertical: 12, height: 1, backgroundColor: WARM_BORDER },
  primaryButton: { borderRadius: 12, paddingVertical: 12, alignItems: 'center', borderWidth: 1 },
  connectButton: { borderColor: ACCENT_COLOR, backgroundColor: 'rgba(242, 157, 78, 0.16)' },
  secondaryButton: { borderColor: WARM_BORDER, backgroundColor: WARM_BG_3 },
  primaryButtonText: { color: '#FFF0DF', fontSize: 14, fontWeight: '700' },
  phasePillWrap: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 12, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 999, borderWidth: 2, borderColor: WARM_BORDER, backgroundColor: WARM_BG_2 },
  phaseDot: { width: 12, height: 12, borderRadius: 99, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.4, shadowRadius: 8, elevation: 6 },
  phaseText: { fontSize: 13, fontWeight: '700', letterSpacing: 0.3 },
  stateCard: { borderRadius: 14, borderWidth: 1, borderColor: WARM_BORDER, backgroundColor: WARM_BG_2, paddingHorizontal: 16, paddingVertical: 20 },
  stateVisualsWrap: { flexDirection: 'row', alignItems: 'center', gap: 20 },
  stateRingsContainer: { width: 100, height: 100, justifyContent: 'center', alignItems: 'center' },
  stateRing: { position: 'absolute', borderWidth: 2 },
  stateRingOuter: { width: 100, height: 100, borderRadius: 50 },
  stateRingMiddle: { width: 70, height: 70, borderRadius: 35 },
  stateCircle: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', elevation: 10 },
  stateEmoji: { fontSize: 20, fontWeight: '700' },
  stateInfoWrap: { flex: 1, justifyContent: 'center' },
  stateStatusLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 1, color: '#B88D69', textTransform: 'uppercase' },
  stateStatusValue: { fontSize: 18, fontWeight: '700', marginTop: 6, letterSpacing: 0.5 },
  stateStatusDetail: { marginTop: 6, fontSize: 12, color: '#C6A98D', lineHeight: 18 },
  stateContentWrap: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  stateIndicatorWrap: { alignItems: 'center', justifyContent: 'center' },
  stateIndicatorOuter: { width: 64, height: 64, borderRadius: 32, borderWidth: 2.5, alignItems: 'center', justifyContent: 'center' },
  stateIndicatorInner: { width: 36, height: 36, borderRadius: 18, elevation: 8 },
  stateTextWrap: { flex: 1 },
  stateLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 1, color: '#B88D69', textTransform: 'uppercase' },
  stateValue: { fontSize: 16, fontWeight: '700', marginTop: 4, letterSpacing: 0.3 },
  statsGrid: { marginTop: 12, flexDirection: 'row', gap: 8 },
  statChip: { flex: 1, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 8, borderWidth: 1, borderColor: WARM_BORDER, backgroundColor: WARM_BG_3 },
  statLabel: { color: '#C6A98D', fontSize: 11, fontWeight: '600' },
  statValue: { marginTop: 4, color: '#FFF0DF', fontSize: 13, fontWeight: '700' },
  liveText: { color: '#E3C6AB', fontSize: 15, fontStyle: 'italic', lineHeight: 22 },
  transcriptCard: { borderLeftWidth: 3, borderLeftColor: '#b49e0d' },
  responseCard: { borderLeftWidth: 3, borderLeftColor: '#48C78E' },
  mainText: { color: '#FFF0DF', fontSize: 16, lineHeight: 24 },
  errorCard: { borderColor: '#6A2D37', backgroundColor: 'rgba(106, 45, 55, 0.28)' },
  errorText: { color: '#FFC5CD', fontSize: 14, lineHeight: 21 },
  serverIndicator: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4 },
  serverIndicatorOnline: { borderColor: '#4CAF50', backgroundColor: 'rgba(76, 175, 80, 0.1)' },
  serverIndicatorOffline: { borderColor: '#FF6B6B', backgroundColor: 'rgba(255, 107, 107, 0.1)' },
  indicatorDot: { width: 6, height: 6, borderRadius: 3 },
  indicatorDotOnline: { backgroundColor: '#4CAF50' },
  indicatorDotOffline: { backgroundColor: '#FF6B6B' },
  navWrapper: { backgroundColor: WARM_BG },
  bottomNav: { borderTopWidth: 1, borderTopColor: WARM_BORDER, backgroundColor: WARM_BG, paddingTop: 6, paddingBottom: 4, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
  navItem: { alignItems: 'center', minWidth: 70, flex: 1, paddingVertical: 6 },
  navGlyph: { color: '#B88D69', fontSize: 18, fontWeight: '700' },
  navGlyphActive: { color: ACCENT_COLOR, fontSize: 18, fontWeight: '800' },
  navLabel: { marginTop: 3, color: '#B88D69', fontWeight: '500' },
  navLabelActive: { marginTop: 3, color: ACCENT_COLOR, fontWeight: '700' },
  activeDot: { marginTop: 4, width: 5, height: 5, borderRadius: 99, backgroundColor: ACCENT_COLOR },
  waveRing: { position: 'absolute', borderWidth: 2, width: 100, height: 100, borderRadius: 50, borderColor: ACCENT_COLOR },
});
